#ifndef TEKKEN7_POINTERS_H
#define TEKKEN7_POINTERS_H

#define TEKKEN_EXE_NAME "TekkenGame-Win64-Shipping.exe"

#define TEKKEN_MODULE_NAME L"TekkenGame-Win64-Shipping.exe"

#define P1_RECOVERY_FRAMES_STATIC_POINTER 0x34EB098
#define P1_RECOVERY_FRAMES_POINTER_OFFSETS {}

#define P1_STATE_STATIC_POINTER 0x34E75A0
#define P1_STATE_POINTER_OFFSETS {}

#define P2_STATE_STATIC_POINTER 0x34EAC10
#define P2_STATE_POINTER_OFFSETS {}

/*
#define P1_STARTUP_FRAMES_STATIC_POINTER P1_RECOVERY_FRAMES_STATIC_POINTER
#define P1_STARTUP_FRAMES_POINTER_OFFSETS {8, 0, 0x7680}

#define P2_STARTUP_FRAMES_STATIC_POINTER P1_RECOVERY_FRAMES_STATIC_POINTER
#define P2_STARTUP_FRAMES_POINTER_OFFSETS {8, 0, 0xEDC0}
*/

#endif
